name: PR Build

on:
  pull_request:
    # when using teardown: 'true', add default event types + closed event type
    types: [opened, synchronize, reopened, closed]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout repository
        if: github.event.action != 'closed'
        uses: actions/checkout@v4

      - name: Install Conda environment with Micromamba
        if: github.event.action != 'closed'
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          cache-environment: true

      - name: Build JupyterBook
        if: github.event.action != 'closed'
        run: |
          jb build book

      - name: Upload artifact
        if: github.event.action != 'closed'
        uses: actions/upload-artifact@v4
        with:
          name: html
          path: book/_build/html
