name: PR Teardown

on:
  pull_request_target:
    types: [closed]

jobs:
  # NOTE: jobname must match deployonly.yml
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Remove Surge.sh PR Preview
        uses: afc163/surge-preview@v1
        with:
          surge_token: ${{ secrets.SURGE_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build: echo 'Removing Surge.sh preview...'
          failOnError: true
          teardown: true
